# fly.toml app configuration file generated for teste-frontend-amicci-bitter-resonance-508 on 2024-04-25T20:56:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teste-frontend-amicci-bitter-resonance-508'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
